name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag dishachaudhari/dockerimage-dockerubuntu:latest
    - name: push the docker image
      run: docker login -u dishachasudhari -p ${{ secrets.DOCKER_TOKEN }} && dpckerpush dishachaudhari/dockerimage-dockerubuntu:latest
